/**
 * Groups of equivalent spellings, no privileged canon: any member expands to all of them.
 * Alternate spellings and abbreviation expansions only, never near-synonyms, so a real gap stays
 * a gap. Ambiguous cross-profession abbreviations (pm, ed, ap, ml, or, pt) are excluded on purpose.
 */
export const SYNONYM_GROUPS: string[][] = [
  ["js", "javascript"],
  ["ts", "typescript"],
  ["nextjs", "next.js", "next"],
  ["nodejs", "node", "node.js"],
  ["postgres", "postgresql"],
  ["k8s", "kubernetes"],
  ["dotnet", ".net", "aspnet"],
  ["golang", "go"],
  ["csharp", "c#"],
  ["react", "reactjs", "react.js"],
  ["sql server", "ms sql", "mssql", "microsoft sql server", "t-sql", "tsql"],
  ["aws", "amazon web services"],
  ["gcp", "google cloud platform"],
  ["azure", "microsoft azure"],
  ["qa", "quality assurance"],
  ["ci cd", "cicd", "continuous integration and continuous delivery"],
  ["cpp", "c++"],
  ["objc", "objective c"],
  ["vue", "vuejs", "vue.js"],
  ["ror", "ruby on rails", "rails"],
  ["gql", "graphql"],
  ["oop", "object oriented programming"],
  ["tdd", "test driven development"],
  ["etl", "extract transform load"],
  ["iac", "infrastructure as code"],
  ["sre", "site reliability engineering", "site reliability engineer"],
  ["ai", "artificial intelligence"],
  ["bi", "business intelligence"],
  ["dbms", "database management system"],
  ["ms office", "microsoft office"],
  ["ms excel", "microsoft excel"],
  ["gsuite", "google workspace"],

  ["rn", "registered nurse"],
  ["lpn", "licensed practical nurse"],
  ["cna", "certified nursing assistant"],
  ["bls", "basic life support"],
  ["acls", "advanced cardiovascular life support"],
  ["pals", "pediatric advanced life support"],
  ["cpr", "cardiopulmonary resuscitation"],
  ["emt", "emergency medical technician"],
  ["np", "nurse practitioner"],
  ["icu", "intensive care unit"],
  ["med surg", "medical surgical"],
  ["ltc", "long term care"],
  ["snf", "skilled nursing facility"],
  ["ehr", "electronic health records", "electronic health record"],
  ["emr", "electronic medical records", "electronic medical record"],
  ["hipaa", "health insurance portability and accountability act"],

  ["cpa", "certified public accountant"],
  ["cfa", "chartered financial analyst"],
  ["cfp", "certified financial planner"],
  ["gaap", "generally accepted accounting principles"],
  ["ifrs", "international financial reporting standards"],
  ["fp&a", "financial planning and analysis"],

  ["pmp", "project management professional"],
  ["okr", "okrs", "objectives and key results"],
  ["kpi", "kpis", "key performance indicators", "key performance indicator"],
  ["erp", "enterprise resource planning"],

  ["crm", "customer relationship management"],
  ["seo", "search engine optimization"],
  ["sem", "search engine marketing"],
  ["ppc", "pay per click"],
  ["smm", "social media marketing"],
  ["abm", "account based marketing"],
  ["b2b", "business to business"],
  ["b2c", "business to consumer"],
  ["saas", "software as a service"],
  ["cpg", "consumer packaged goods"],
  ["pos", "point of sale"],
  ["roi", "return on investment"],
  ["sdr", "sales development representative"],
  ["bdr", "business development representative"],

  ["ux", "user experience"],
  ["ui", "user interface"],
  ["cad", "computer aided design"],

  ["cdl", "commercial drivers license", "commercial driver's license"],
  ["hvac", "heating ventilation and air conditioning"],
  ["osha", "occupational safety and health administration"],
  ["epa", "environmental protection agency"],
  ["cnc", "computer numerical control"],
  ["plc", "programmable logic controller"],
  ["gmp", "good manufacturing practice", "good manufacturing practices"],
  ["3pl", "third party logistics"],
  ["wms", "warehouse management system"],
  ["cmms", "computerized maintenance management system"],
  ["sop", "standard operating procedure", "standard operating procedures"],

  ["esl", "english as a second language"],
  ["iep", "individualized education program", "individualized education plan"],
  ["sped", "special education"],

  ["hris", "human resources information system"],
  ["ats", "applicant tracking system"],
  ["fmla", "family and medical leave act"],
  ["eeo", "equal employment opportunity"],
];
